"""Provider request and response models."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import Any

from qceval.models.types import Framework, ProviderRole
from qceval.serialization import to_jsonable


@dataclass(frozen=True)
class ProviderMessage:
    """One chat message sent to a conversation-capable provider.

    Attributes:
        role: Chat role for the message.
        content: Message text.
    """

    role: ProviderRole
    content: str


@dataclass(frozen=True)
class TokenUsage:
    """Token accounting reported by providers when available.

    Providers may omit any field they cannot report.  The runner records the
    object without interpreting the values, which keeps provider-specific token
    accounting out of the benchmark semantics.

    Attributes:
        prompt_tokens: Number of input tokens consumed by the request.
        completion_tokens: Number of output tokens generated by the provider.
        total_tokens: Provider-reported total token count.
        reasoning_tokens: Provider-reported reasoning token count, if exposed.
        cached_tokens: Provider-reported cached prompt token count, if exposed.
        cost_usd: Provider-reported request cost in US dollars, if exposed.
    """

    prompt_tokens: int | None = None
    completion_tokens: int | None = None
    total_tokens: int | None = None
    reasoning_tokens: int | None = None
    cached_tokens: int | None = None
    cost_usd: float | None = None

    def to_dict(self) -> dict[str, int | float | None]:
        """Return JSON-compatible token usage data."""
        return to_jsonable(self)


@dataclass(frozen=True)
class ProviderRequest:
    """Input passed to a provider for one framework task.

    ``ProviderRequest`` is the only benchmark object a provider must understand.
    It carries the natural-language prompt, the expected function name, and
    optional metadata such as canonical solutions for smoke testing.

    Attributes:
        task_id: Zero-padded task identifier within ``framework``.
        framework: Quantum framework targeted by the task.
        prompt: Prompt text the provider should answer with Python code.
        entry_point: Function name the generated code must define.
        model: Optional model identifier chosen by the caller.
        metadata: Extra task metadata intended for provider implementations.
        sample_index: Repeated-sample index for Pass@K runs.
        attempt_index: Feedback-repair attempt index.
        messages: Optional chat history for multi-turn providers.
    """

    task_id: str
    framework: Framework
    prompt: str
    entry_point: str
    model: str | None = None
    metadata: Mapping[str, Any] = field(default_factory=dict)
    sample_index: int = 0
    attempt_index: int = 0
    messages: tuple[ProviderMessage, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        """Return JSON-compatible provider request data."""
        return to_jsonable(self)


@dataclass(frozen=True)
class ProviderResponse:
    """Code-generation result returned by a provider.

    A response can represent either usable code or a provider-side failure.  The
    runner does not raise provider exceptions; provider implementations should
    capture failures in ``error`` so results remain serializable and resumable.

    Attributes:
        code: Candidate Python source, or ``None`` when generation failed.
        model: Provider-reported model identifier.
        metadata: Provider-specific response metadata.
        usage: Optional token usage.
        raw_response: Optional raw provider payload.  Caches strip this field.
        error: Provider-side error message, if generation failed.
    """

    code: str | None
    model: str | None = None
    metadata: Mapping[str, Any] = field(default_factory=dict)
    usage: TokenUsage | None = None
    raw_response: Any | None = None
    error: str | None = None

    @property
    def ok(self) -> bool:
        """Return whether the response contains nonempty candidate code."""
        return self.error is None and self.code is not None and bool(self.code.strip())

    def to_dict(self) -> dict[str, Any]:
        """Return JSON-compatible provider response data."""
        return to_jsonable(self)
